theme: jekyll-theme-minimal

title: Eesh Gupta
description: Undergraduate Student in Physics
description2: Rutgers University

contact: eesh.gupta@rutgers.edu
logo: /images/profile.png
show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]
