theme: jekyll-theme-minimal

title: Eesh Gupta
description: Undergraduate Student in Physics at Rutgers University

cv_link: /documents/CV.pdf
email: eesh.gupta@rutgers.edu
logo: /images/profile.png
show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]
