theme: jekyll-theme-minimal

title: Eesh Gupta
description: Undergraduate Student in Physics at Rutgers University

email: eag4013@gmail.com
show_downloads: "false"
# plugins: - jekyll-sitemap
#google_analytics: [Your Google Analytics tracking ID]
