theme: jekyll-theme-minimal

title: Eesh Gupta
logo: images/Eesh2023_final.jpg
email: eesh.gupta.pro@gmail.com
cv_link: https://drive.google.com/file/d/1co1ZU9F10K80tcZIyaK75cqDabvMcuaY/view?usp=sharing
show_downloads: "false"
#description: Graduate Student
# plugins: - jekyll-sitemap
#google_analytics: [Your Google Analytics tracking ID]
