theme: jekyll-theme-minimal

title: Eesh Gupta
description: Undergraduate Student in Physics at Rutgers University

logo: /images/profile.png
show_downloads: "false"
#google_analytics: [Your Google Analytics tracking ID]
