theme: jekyll-theme-minimal

title: Eesh Gupta
description: Undergraduate Student in Physics at Rutgers University

cv_link: https://github.com/EeshGupta/eeshgupta.github.io/blob/main/documents/CVJan4.pdf
email: eesh.gupta@rutgers.edu
logo: /images/profile.jpg
show_downloads: "false"
# plugins: - jekyll-sitemap
#google_analytics: [Your Google Analytics tracking ID]
